# Generated by Django 4.0.3 on 2022-03-08 22:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ewasteapp', '0002_alter_customuser_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_name',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=150, unique=True),
        ),
    ]
