# Generated by Django 4.0.3 on 2022-03-08 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ewasteapp', '0003_alter_customuser_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
