# Generated by Django 4.0.3 on 2022-03-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewasteapp', '0004_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_name',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
    ]
